In [1]:
import torch

In [9]:
a = torch.nn.Embedding(3,10)

In [8]:
b = torch.nn.Embedding(3,10)

In [11]:
soft = torch.nn.Softmax(dim=-1)

In [ ]:
a = a.weight
b = b.weight

In [13]:
sim = torch.matmul(a,b.T)
sim = soft(sim)

In [14]:
sim

tensor([[0.0179, 0.7890, 0.1931],
        [0.3656, 0.0531, 0.5813],
        [0.0315, 0.0176, 0.9509]], grad_fn=<SoftmaxBackward>)

In [16]:
diag = torch.diag(sim)
diag = torch.diag_embed(diag)
diag

tensor([[0.0179, 0.0000, 0.0000],
        [0.0000, 0.0531, 0.0000],
        [0.0000, 0.0000, 0.9509]], grad_fn=<CopySlices>)

In [19]:
after = torch.matmul(diag,b)

In [20]:
torch.matmul(a,after.T)

tensor([[-0.0407,  0.0803,  0.0998],
        [ 0.0302, -0.0128,  2.0459],
        [ 0.0040, -0.0190,  3.4518]], grad_fn=<MmBackward>)

In [39]:
import numpy as np
sigma_all = torch.nn.Embedding(100, 10)
los = np.array([[1,2,3,4,5],[2,3,4,5,6]])
uui = np.array([[1],[2]])
sigma_all.weight[[1,2,3,4,5,6]]

tensor([[-0.2119, -0.6658,  0.9436, -1.1883,  0.3779,  2.2677, -0.4740, -1.0031,
          0.2273,  0.5684],
        [ 0.5765, -0.5859, -0.3571, -0.1337, -0.8380,  0.0686,  2.3197, -1.6173,
          1.5192, -1.0353],
        [-0.6227,  2.1033,  0.4209, -0.3080, -0.8228, -0.2850,  0.6182, -0.6425,
         -0.4790,  0.8435],
        [ 0.2144, -0.1892, -1.8633, -0.1442, -0.0238, -0.6431,  2.0661,  1.4113,
         -1.2297, -0.6453],
        [-0.6622, -0.0423, -1.2910, -0.2876,  1.0808,  1.1743, -0.1437,  1.9958,
         -0.3511, -0.9113],
        [ 0.2043, -0.0423, -0.2082,  0.4873, -0.6578,  0.2642, -0.9282, -0.5552,
         -1.3128, -0.7613]], grad_fn=<IndexBackward>)

In [40]:
sigma_all.weight[uui,los]

tensor([[-0.6658,  0.9436, -1.1883,  0.3779,  2.2677],
        [-0.3571, -0.1337, -0.8380,  0.0686,  2.3197]],
       grad_fn=<IndexBackward>)

In [41]:
%run main.py

Namespace(abs_num_heads=10, batch_size=1024, beta=0.02, beta_c=0.02, dataset='Beauty', device='cuda:1', dropout_rate=0.5, gcn_layer=4, gcn_layer_c=4, hidden_units=50, inference_only=False, l2_emb=0.0001, lr=0.0001, maxlen=20, num_blocks=2, num_epochs=501, num_heads=10, state_dict_path=None, train_dir='default')
data processing done...


/home/machery/Untitled Folder/re_TIAC_test/utils.py:140: RuntimeWarning: divide by zero encountered in power
  d_inv = np.power(rowsum, -1).flatten()


time interval processing done...
time interval processing done...
generate single-normalized adjacency matrix.
generate single-normalized adjacency matrix.
generate single-normalized adjacency matrix.
generate single-normalized adjacency matrix.
split..Preparing done...
train average sequence length: 6.88
the tensorboard start time and filename are  02-23-23h03m04s-


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.34it/s]


epoch is 20,NDCG is 0.1771072023096288, HR is 0.3171 MRR is 0.1345350396825396 time is 78.50384879112244


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.13it/s]


epoch is 40,NDCG is 0.2105285472061504, HR is 0.3676 MRR is 0.16253353174603116 time is 79.15969276428223


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.43it/s]


epoch is 60,NDCG is 0.22629681617350064, HR is 0.3964 MRR is 0.17442904761904665 time is 79.17566251754761


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.69it/s]


epoch is 80,NDCG is 0.24568355433975758, HR is 0.4254 MRR is 0.19060289682539552 time is 78.38736820220947


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.49it/s]


epoch is 100,NDCG is 0.2599293287875371, HR is 0.452 MRR is 0.20110511904761774 time is 78.379567861557


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.67it/s]


epoch is 120,NDCG is 0.26591569151183175, HR is 0.4567 MRR is 0.20740373015872887 time is 78.56355261802673


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.68it/s]


epoch is 140,NDCG is 0.27653293344481295, HR is 0.4674 MRR is 0.21801674603174537 time is 78.3859806060791


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.59it/s]


epoch is 160,NDCG is 0.2890248878282538, HR is 0.4863 MRR is 0.2284368650793641 time is 77.71550726890564


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.47it/s]


epoch is 180,NDCG is 0.29285320259745823, HR is 0.492 MRR is 0.2316594047619039 time is 78.44665050506592


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.41it/s]


epoch is 200,NDCG is 0.2991288626904261, HR is 0.492 MRR is 0.23972420634920621 time is 78.41784310340881


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.19it/s]


epoch is 220,NDCG is 0.3062429964500266, HR is 0.4942 MRR is 0.24818305555555517 time is 78.74670648574829


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.64it/s]


epoch is 240,NDCG is 0.31241074132916163, HR is 0.5022 MRR is 0.2535947222222226 time is 78.46468210220337


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.63it/s]


epoch is 260,NDCG is 0.3100682849515412, HR is 0.4974 MRR is 0.25208424603174573 time is 79.01618814468384


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.54it/s]


epoch is 280,NDCG is 0.31342388199232796, HR is 0.5014 MRR is 0.25535936507936496 time is 78.80722379684448


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.62it/s]


epoch is 300,NDCG is 0.3193736268870289, HR is 0.5079 MRR is 0.2609723015873018 time is 78.56029558181763


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.52it/s]


epoch is 320,NDCG is 0.3158161619485014, HR is 0.5034 MRR is 0.25777480158730154 time is 78.77218055725098


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.66it/s]


epoch is 340,NDCG is 0.32367885313302364, HR is 0.5062 MRR is 0.2670138095238102 time is 78.62689137458801


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.71it/s]


epoch is 360,NDCG is 0.32116155424694776, HR is 0.5072 MRR is 0.26348079365079397 time is 78.41508650779724


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.36it/s]


epoch is 380,NDCG is 0.3261672299891664, HR is 0.5077 MRR is 0.2699157936507939 time is 78.63078141212463


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.36it/s]


epoch is 400,NDCG is 0.3217559428931716, HR is 0.5052 MRR is 0.2648049206349202 time is 78.53642725944519


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.28it/s]


epoch is 420,NDCG is 0.3316281422882384, HR is 0.5123 MRR is 0.2755037301587308 time is 78.89536714553833


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.76it/s]


epoch is 440,NDCG is 0.32471857426673867, HR is 0.5071 MRR is 0.26822428571428586 time is 78.52470898628235


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.73it/s]


epoch is 460,NDCG is 0.32227733716694795, HR is 0.5026 MRR is 0.2664696428571429 time is 78.50260424613953


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.57it/s]


epoch is 480,NDCG is 0.33162750945567265, HR is 0.5175 MRR is 0.2740786111111113 time is 78.5760440826416


Testing: 100%|██████████| 10/10 [00:01<00:00,  9.54it/s]


epoch is 500,NDCG is 0.32378731610686945, HR is 0.5015 MRR is 0.26870829365079413 time is 78.46963024139404


Training: 100%|██████████| 21/21 [00:03<00:00,  5.90it/s]


Done
max NDCG is 0.3316281422882384, max HR is 0.5175 max MRR is 0.2755037301587308
